# Generated by Django 6.1.1 on 2026-09-27 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(help_text="The main question, e.g. 'How do I donate?'", max_length=255)),
                ('keywords', models.CharField(help_text='Comma-separated keywords that should trigger this answer, e.g. donate, donation, give money', max_length=255)),
                ('answer', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
